pipeline {
    agent any
    stages {
        stage("Build Frontend") {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/FelipeBaeza/PrestaBancoEntrega']])
                dir("TingesoFront") {
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image") {
            steps {
                dir("TingesoFront") {
                    script {
                        bat "docker context use default"
                        withDockerRegistry(credentialsId: 'docker-credentials') {
                            bat "docker build -t felipeb2001/frontend-image ."
                            bat "docker push felipeb2001/front-image"
                        }
                    }
                }
            }
        }
    }
}