pipeline{
    agent any
    stages{
        stage('Build Frontend'){
            steps{
                checkout scmGit(branches: [[name: 'refs/heads/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/FelipeBaeza/PrestaBancoEntrega']])
                dir("TingesoFront"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage('Build and Push Docker Image'){
            steps{
                dir("TingesoFront"){
                    script{
                        withDockerRegistry(credentialsId: 'docker-credenciales'){
                            bat "docker build -t felipeb2001/front-image ."
                            bat "docker push felipeb2001/front-image"
                        }
                    }
                }
            }
        }
    }
}