version: '3.8'

services:
  # Nginx backend server
  nginx-backend:
    image: nginx:latest
    container_name: presta-banco-nginx-backend-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./backend.conf:/etc/nginx/nginx.conf
    networks:
      - presta-banco-backend-network
    depends_on:
      - spring1
      - spring2
      - spring3

  # Nginx frontend server
  nginx-frontend:
    image: nginx:latest
    container_name: presta-banco-nginx-frontend-container
    restart: always
    ports:
      - 8070:8070
    volumes:
      - ./frontend.conf:/etc/nginx/nginx.conf
    networks:
      - presta-banco-frontend-network
    depends_on:
      - react1
      - react2
      - react3

  # PostgreSQL service
  postgres:
    container_name: presta-banco-postgres-container
    image: postgres
    restart: on-failure
    volumes:
      - presta-banco-postgres-volume:/var/lib/postgresql/data
    networks:
      - presta-banco-backend-network
    environment:
      POSTGRES_PASSWORD: felipeb222
      POSTGRES_DB: bd-tingeso
    ports:
      - 5435:5432

  # Spring backend services
  spring1:
    container_name: presta-banco-backend-container-1
    image: felipeb2001/backend-image
    ports:
      - 8081:8080
    environment:
      ADDRESS: presta-banco-postgres-container
      PORT: 5432
      DB_NAME: bd-tingeso
      DB_USERNAME: postgres
      DB_PASSWORD: felipeb222
    networks:
      - presta-banco-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres

  spring2:
    container_name: presta-banco-backend-container-2
    image: felipeb2001/backend-image
    ports:
      - 8082:8080
    environment:
      ADDRESS: presta-banco-postgres-container
      PORT: 5432
      DB_NAME: bd-tingeso
      DB_USERNAME: postgres
      DB_PASSWORD: felipeb222
    networks:
      - presta-banco-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres

  spring3:
    container_name: presta-banco-backend-container-3
    image: felipeb2001/backend-image
    ports:
      - 8083:8080
    environment:
      ADDRESS: presta-banco-postgres-container
      PORT: 5432
      DB_NAME: bd-tingeso
      DB_USERNAME: postgres
      DB_PASSWORD: felipeb222
    networks:
      - presta-banco-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres

  # React frontend services
  react1:
    container_name: presta-banco-frontend-container-1
    image: felipeb2001/frontend-image
    ports:
      - 3001:3000
    networks:
      - presta-banco-frontend-network
    deploy:
      restart_policy:
        condition: on-failure

  react2:
    container_name: presta-banco-frontend-container-2
    image: felipeb2001/frontend-image
    ports:
      - 3002:3000
    networks:
      - presta-banco-frontend-network
    deploy:
      restart_policy:
        condition: on-failure

  react3:
    container_name: presta-banco-frontend-container-3
    image: felipeb2001/frontend-image
    ports:
      - 3003:3000
    networks:
      - presta-banco-frontend-network
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  presta-banco-postgres-volume:

networks:
  presta-banco-backend-network:
  presta-banco-frontend-network: